


const MainData=[
    {id:5, image:"https://tmbidigitalassetsazure.blob.core.windows.net/rms3-prod/attachments/37/1200x1200/Pizza-from-Scratch_EXPS_FT20_8621_F_0505_1_home.jpg",name:"Pizza from Scratch",discription:"Turn onto a floured surface; knead until smooth and elastic, 6-8 minutes. Place in a greased bowl, turning once to grease top. Cover and let rest in a warm place for 10 minutes.",price:10,quantity:100 },
    {id:4, image:"https://insanelygoodrecipes.com/wp-content/uploads/2020/04/Fried_Chicken-1024x536.png",name:"Pizza from Scratch",discription:"Turn onto a floured surface; knead until smooth and elastic, 6-8 minutes. Place in a greased bowl, turning once to grease top. Cover and let rest in a warm place for 10 minutes.",price:10,quantity:100 },
    {id:3,image:"https://tmbidigitalassetsazure.blob.core.windows.net/rms3-prod/attachments/37/1200x1200/Pizza-from-Scratch_EXPS_FT20_8621_F_0505_1_home.jpg",name:"Pizza from Scratch",discription:"Turn onto a floured surface; knead until smooth and elastic, 6-8 minutes. Place in a greased bowl, turning once to grease top. Cover and let rest in a warm place for 10 minutes.",price:10,quantity:100 },
    {id:1,image:"https://tmbidigitalassetsazure.blob.core.windows.net/rms3-prod/attachments/37/1200x1200/Pizza-from-Scratch_EXPS_FT20_8621_F_0505_1_home.jpg",name:"Pizza from Scratch",discription:"Turn onto a floured surface; knead until smooth and elastic, 6-8 minutes. Place in a greased bowl, turning once to grease top. Cover and let rest in a warm place for 10 minutes.",price:10,quantity:100 },
    {id:10,image:"https://tmbidigitalassetsazure.blob.core.windows.net/rms3-prod/attachments/37/1200x1200/Pizza-from-Scratch_EXPS_FT20_8621_F_0505_1_home.jpg",name:"Pizza from Scratch",discription:"Turn onto a floured surface; knead until smooth and elastic, 6-8 minutes. Place in a greased bowl, turning once to grease top. Cover and let rest in a warm place for 10 minutes.",price:10,quantity:100 },
    {id:8,image:"https://tmbidigitalassetsazure.blob.core.windows.net/rms3-prod/attachments/37/1200x1200/Pizza-from-Scratch_EXPS_FT20_8621_F_0505_1_home.jpg",name:"Pizza from Scratch",discription:"Turn onto a floured surface; knead until smooth and elastic, 6-8 minutes. Place in a greased bowl, turning once to grease top. Cover and let rest in a warm place for 10 minutes.",price:10,quantity:100 },
    {id:19,image:"https://tmbidigitalassetsazure.blob.core.windows.net/rms3-prod/attachments/37/1200x1200/Pizza-from-Scratch_EXPS_FT20_8621_F_0505_1_home.jpg",name:"Pizza from Scratch",discription:"Turn onto a floured surface; knead until smooth and elastic, 6-8 minutes. Place in a greased bowl, turning once to grease top. Cover and let rest in a warm place for 10 minutes.",price:10,quantity:100 },
    {id:11,image:"https://tmbidigitalassetsazure.blob.core.windows.net/rms3-prod/attachments/37/1200x1200/Pizza-from-Scratch_EXPS_FT20_8621_F_0505_1_home.jpg",name:"Pizza from Scratch",discription:"Turn onto a floured surface; knead until smooth and elastic, 6-8 minutes. Place in a greased bowl, turning once to grease top. Cover and let rest in a warm place for 10 minutes.",price:10,quantity:100 },
    {id:17,image:"https://tmbidigitalassetsazure.blob.core.windows.net/rms3-prod/attachments/37/1200x1200/Pizza-from-Scratch_EXPS_FT20_8621_F_0505_1_home.jpg",name:"Pizza from Scratch",discription:"Turn onto a floured surface; knead until smooth and elastic, 6-8 minutes. Place in a greased bowl, turning once to grease top. Cover and let rest in a warm place for 10 minutes.",price:10,quantity:100 },
]

export default MainData